site_name: MapLibre for Python

theme:
  name: material
  custom_dir: docs/theme
  palette:
    primary: "green"
  features:
    - navigation.tabs
    - navigation.tabs.sticky

nav:
  - Get started:
      - Welcome to MapLibre: index.md
      - Layers: layers.md
      - Deck.GL Layers: deckgl.md
      - Shiny: shiny.md
      - Jupyter: jupyter.md
      - Streamlit: streamlit.md
      - Changelog: changelog.md
  - API Documentation:
      - Map: api/map.md
      - Layer: api/layer.md
      - Sources: api/sources.md
      - Basemaps: api/basemaps.md
      - Markers and controls: api/controls.md
  - Examples:
      - Every Person in Manhattan: examples/every_person_in_manhattan/index.md
      - Vancouver Property Value: examples/vancouver_blocks/index.md
      - Earthquake Clusters: examples/earthquake_clusters/index.md
      - Airport Markers: examples/airports/index.md
      - 3D Indoor Mapping: examples/3d_indoor_mapping/index.md
      - Custom basemap: examples/custom_basemap/index.md
      - GeoPandas: examples/geopandas/index.md
      - H3 Grid UK Road Safety: examples/road_safety/index.md
      - Where is the ISS: examples/where_is_the_iss/index.md
      - WMS: examples/wms/index.md
      - Layer Order: examples/layer_order/index.md
      - Deck.GL Layer: examples/deckgl_layer/index.md
      - Multiple Deck.GL Layers: examples/deckgl_multiple_layers/index.md
      - PMTiles: examples/pmtiles/index.md
      - Mapbox Draw Plugin: examples/mapbox_draw_plugin/index.md
      - Layer Switcher: examples/layer_switcher/index.md
plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            docstring_section_style: table
            show_root_heading: true
            show_source: True

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.snippets:
      check_paths: true
      base_path: [docs/examples, "."]

repo_name: py-maplibregl
repo_url: https://github.com/eodaGmbH/py-maplibregl